// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CategoryListResponse struct {
	Code    int64            `json:"code"`
	Message string           `json:"message"`
	Data    []LedgerCategory `json:"data"`
}

type CategoryResponse struct {
	Code    int64          `json:"code"`
	Message string         `json:"message"`
	Data    LedgerCategory `json:"data"`
}

type CategoryStatistics struct {
	CategoryId   int64   `json:"category_id"`
	CategoryName string  `json:"category_name"`
	Amount       float64 `json:"amount"`
	Percentage   float64 `json:"percentage"`
}

type CommonResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type CreateCategoryRequest struct {
	Name      string `json:"name" validate:"required,max=100"`
	Icon      string `json:"icon,optional"`
	Color     string `json:"color,optional"`
	Type      int64  `json:"type" validate:"required,min=1,max=2"`
	SortOrder int64  `json:"sort_order,optional"`
}

type CreateLedgerRecordRequest struct {
	CategoryId    int64    `json:"category_id" validate:"required"`
	SubCategoryId int64    `json:"sub_category_id,optional"`
	Amount        float64  `json:"amount" validate:"required,min=0.01"`
	Type          int64    `json:"type" validate:"required,min=1,max=2"`
	Description   string   `json:"description,optional"`
	Note          string   `json:"note,optional"`
	RecordDate    string   `json:"record_date" validate:"required"`
	Tags          []string `json:"tags,optional"`
	Location      string   `json:"location,optional"`
	Images        []string `json:"images,optional"`
}

type CreateSubCategoryRequest struct {
	CategoryId int64  `json:"category_id" validate:"required"`
	Name       string `json:"name" validate:"required,max=100"`
	Icon       string `json:"icon,optional"`
	Color      string `json:"color,optional"`
	SortOrder  int64  `json:"sort_order,optional"`
}

type DeleteCategoryRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type DeleteLedgerRecordRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type DeleteLedgerRecordResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type DeleteSubCategoryRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type LedgerCategory struct {
	Id        int64  `json:"id"`
	UserId    int64  `json:"user_id"`
	Name      string `json:"name"`
	Icon      string `json:"icon"`
	Color     string `json:"color"`
	Type      int64  `json:"type"` // 1: 收入, 2: 支出
	SortOrder int64  `json:"sort_order"`
	IsSystem  bool   `json:"is_system"`
	Status    int64  `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type LedgerRecord struct {
	Id            int64    `json:"id"`
	UserId        int64    `json:"user_id"`
	CategoryId    int64    `json:"category_id"`
	SubCategoryId int64    `json:"sub_category_id,optional"`
	Amount        float64  `json:"amount"`
	Type          int64    `json:"type"` // 1: 收入, 2: 支出
	Description   string   `json:"description"`
	Note          string   `json:"note"`
	RecordDate    string   `json:"record_date"`
	Tags          []string `json:"tags"`
	Location      string   `json:"location"`
	Images        []string `json:"images"`
	Status        int64    `json:"status"`
	CreatedAt     string   `json:"created_at"`
	UpdatedAt     string   `json:"updated_at"`
}

type LedgerRecordDetailRequest struct {
	Id int64 `path:"id" validate:"required"`
}

type LedgerRecordListData struct {
	List     []LedgerRecord `json:"list"`
	Total    int64          `json:"total"`
	Page     int64          `json:"page"`
	PageSize int64          `json:"page_size"`
}

type LedgerRecordListRequest struct {
	Page       int64  `form:"page,optional,default=1"`
	PageSize   int64  `form:"page_size,optional,default=20"`
	CategoryId int64  `form:"category_id,optional"`
	Type       int64  `form:"type,optional"`
	StartDate  string `form:"start_date,optional"`
	EndDate    string `form:"end_date,optional"`
	Keyword    string `form:"keyword,optional"`
}

type LedgerRecordListResponse struct {
	Code    int64                `json:"code"`
	Message string               `json:"message"`
	Data    LedgerRecordListData `json:"data"`
}

type LedgerRecordResponse struct {
	Code    int64        `json:"code"`
	Message string       `json:"message"`
	Data    LedgerRecord `json:"data"`
}

type LedgerStatisticsData struct {
	TotalIncome   float64              `json:"total_income"`
	TotalExpense  float64              `json:"total_expense"`
	Balance       float64              `json:"balance"`
	CategoryStats []CategoryStatistics `json:"category_stats"`
}

type LedgerStatisticsRequest struct {
	StartDate string `form:"start_date,optional"`
	EndDate   string `form:"end_date,optional"`
	Type      int64  `form:"type,optional"`
}

type LedgerStatisticsResponse struct {
	Code    int64                `json:"code"`
	Message string               `json:"message"`
	Data    LedgerStatisticsData `json:"data"`
}

type LedgerSubCategory struct {
	Id         int64  `json:"id"`
	CategoryId int64  `json:"category_id"`
	UserId     int64  `json:"user_id"`
	Name       string `json:"name"`
	Icon       string `json:"icon"`
	Color      string `json:"color"`
	SortOrder  int64  `json:"sort_order"`
	Status     int64  `json:"status"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type SubCategoryListRequest struct {
	CategoryId int64 `form:"category_id,optional"`
}

type SubCategoryListResponse struct {
	Code    int64               `json:"code"`
	Message string              `json:"message"`
	Data    []LedgerSubCategory `json:"data"`
}

type SubCategoryResponse struct {
	Code    int64             `json:"code"`
	Message string            `json:"message"`
	Data    LedgerSubCategory `json:"data"`
}

type UpdateCategoryRequest struct {
	Id        int64  `path:"id" validate:"required"`
	Name      string `json:"name,optional"`
	Icon      string `json:"icon,optional"`
	Color     string `json:"color,optional"`
	Type      int64  `json:"type,optional"`
	SortOrder int64  `json:"sort_order,optional"`
	Status    int64  `json:"status,optional"`
}

type UpdateLedgerRecordRequest struct {
	Id            int64    `path:"id" validate:"required"`
	CategoryId    int64    `json:"category_id,optional"`
	SubCategoryId int64    `json:"sub_category_id,optional"`
	Amount        float64  `json:"amount,optional"`
	Type          int64    `json:"type,optional"`
	Description   string   `json:"description,optional"`
	Note          string   `json:"note,optional"`
	RecordDate    string   `json:"record_date,optional"`
	Tags          []string `json:"tags,optional"`
	Location      string   `json:"location,optional"`
	Images        []string `json:"images,optional"`
	Status        int64    `json:"status,optional"`
}

type UpdateSubCategoryRequest struct {
	Id         int64  `path:"id" validate:"required"`
	CategoryId int64  `json:"category_id,optional"`
	Name       string `json:"name,optional"`
	Icon       string `json:"icon,optional"`
	Color      string `json:"color,optional"`
	SortOrder  int64  `json:"sort_order,optional"`
	Status     int64  `json:"status,optional"`
}
