// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: service/ledger/rpc/ledger.proto

package ledger

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerService_CreateLedgerRecord_FullMethodName    = "/ledger.LedgerService/CreateLedgerRecord"
	LedgerService_UpdateLedgerRecord_FullMethodName    = "/ledger.LedgerService/UpdateLedgerRecord"
	LedgerService_DeleteLedgerRecord_FullMethodName    = "/ledger.LedgerService/DeleteLedgerRecord"
	LedgerService_GetLedgerRecordList_FullMethodName   = "/ledger.LedgerService/GetLedgerRecordList"
	LedgerService_GetLedgerRecordDetail_FullMethodName = "/ledger.LedgerService/GetLedgerRecordDetail"
	LedgerService_CreateCategory_FullMethodName        = "/ledger.LedgerService/CreateCategory"
	LedgerService_UpdateCategory_FullMethodName        = "/ledger.LedgerService/UpdateCategory"
	LedgerService_DeleteCategory_FullMethodName        = "/ledger.LedgerService/DeleteCategory"
	LedgerService_GetCategoryList_FullMethodName       = "/ledger.LedgerService/GetCategoryList"
	LedgerService_CreateSubCategory_FullMethodName     = "/ledger.LedgerService/CreateSubCategory"
	LedgerService_UpdateSubCategory_FullMethodName     = "/ledger.LedgerService/UpdateSubCategory"
	LedgerService_DeleteSubCategory_FullMethodName     = "/ledger.LedgerService/DeleteSubCategory"
	LedgerService_GetSubCategoryList_FullMethodName    = "/ledger.LedgerService/GetSubCategoryList"
	LedgerService_GetLedgerStatistics_FullMethodName   = "/ledger.LedgerService/GetLedgerStatistics"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 记账服务定义
type LedgerServiceClient interface {
	// 记账记录操作
	CreateLedgerRecord(ctx context.Context, in *CreateLedgerRecordRequest, opts ...grpc.CallOption) (*CreateLedgerRecordResponse, error)
	UpdateLedgerRecord(ctx context.Context, in *UpdateLedgerRecordRequest, opts ...grpc.CallOption) (*UpdateLedgerRecordResponse, error)
	DeleteLedgerRecord(ctx context.Context, in *DeleteLedgerRecordRequest, opts ...grpc.CallOption) (*DeleteLedgerRecordResponse, error)
	GetLedgerRecordList(ctx context.Context, in *LedgerRecordListRequest, opts ...grpc.CallOption) (*LedgerRecordListResponse, error)
	GetLedgerRecordDetail(ctx context.Context, in *LedgerRecordDetailRequest, opts ...grpc.CallOption) (*CreateLedgerRecordResponse, error)
	// 分类操作
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
	UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
	GetCategoryList(ctx context.Context, in *CategoryListRequest, opts ...grpc.CallOption) (*CategoryListResponse, error)
	// 子分类操作
	CreateSubCategory(ctx context.Context, in *CreateSubCategoryRequest, opts ...grpc.CallOption) (*CreateSubCategoryResponse, error)
	UpdateSubCategory(ctx context.Context, in *UpdateSubCategoryRequest, opts ...grpc.CallOption) (*UpdateSubCategoryResponse, error)
	DeleteSubCategory(ctx context.Context, in *DeleteSubCategoryRequest, opts ...grpc.CallOption) (*DeleteSubCategoryResponse, error)
	GetSubCategoryList(ctx context.Context, in *SubCategoryListRequest, opts ...grpc.CallOption) (*SubCategoryListResponse, error)
	// 统计操作
	GetLedgerStatistics(ctx context.Context, in *LedgerStatisticsRequest, opts ...grpc.CallOption) (*LedgerStatisticsResponse, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) CreateLedgerRecord(ctx context.Context, in *CreateLedgerRecordRequest, opts ...grpc.CallOption) (*CreateLedgerRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLedgerRecordResponse)
	err := c.cc.Invoke(ctx, LedgerService_CreateLedgerRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) UpdateLedgerRecord(ctx context.Context, in *UpdateLedgerRecordRequest, opts ...grpc.CallOption) (*UpdateLedgerRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLedgerRecordResponse)
	err := c.cc.Invoke(ctx, LedgerService_UpdateLedgerRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) DeleteLedgerRecord(ctx context.Context, in *DeleteLedgerRecordRequest, opts ...grpc.CallOption) (*DeleteLedgerRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLedgerRecordResponse)
	err := c.cc.Invoke(ctx, LedgerService_DeleteLedgerRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetLedgerRecordList(ctx context.Context, in *LedgerRecordListRequest, opts ...grpc.CallOption) (*LedgerRecordListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedgerRecordListResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetLedgerRecordList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetLedgerRecordDetail(ctx context.Context, in *LedgerRecordDetailRequest, opts ...grpc.CallOption) (*CreateLedgerRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLedgerRecordResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetLedgerRecordDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCategoryResponse)
	err := c.cc.Invoke(ctx, LedgerService_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCategoryResponse)
	err := c.cc.Invoke(ctx, LedgerService_UpdateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCategoryResponse)
	err := c.cc.Invoke(ctx, LedgerService_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetCategoryList(ctx context.Context, in *CategoryListRequest, opts ...grpc.CallOption) (*CategoryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryListResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetCategoryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) CreateSubCategory(ctx context.Context, in *CreateSubCategoryRequest, opts ...grpc.CallOption) (*CreateSubCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubCategoryResponse)
	err := c.cc.Invoke(ctx, LedgerService_CreateSubCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) UpdateSubCategory(ctx context.Context, in *UpdateSubCategoryRequest, opts ...grpc.CallOption) (*UpdateSubCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubCategoryResponse)
	err := c.cc.Invoke(ctx, LedgerService_UpdateSubCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) DeleteSubCategory(ctx context.Context, in *DeleteSubCategoryRequest, opts ...grpc.CallOption) (*DeleteSubCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSubCategoryResponse)
	err := c.cc.Invoke(ctx, LedgerService_DeleteSubCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetSubCategoryList(ctx context.Context, in *SubCategoryListRequest, opts ...grpc.CallOption) (*SubCategoryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubCategoryListResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetSubCategoryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetLedgerStatistics(ctx context.Context, in *LedgerStatisticsRequest, opts ...grpc.CallOption) (*LedgerStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedgerStatisticsResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetLedgerStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
//
// 记账服务定义
type LedgerServiceServer interface {
	// 记账记录操作
	CreateLedgerRecord(context.Context, *CreateLedgerRecordRequest) (*CreateLedgerRecordResponse, error)
	UpdateLedgerRecord(context.Context, *UpdateLedgerRecordRequest) (*UpdateLedgerRecordResponse, error)
	DeleteLedgerRecord(context.Context, *DeleteLedgerRecordRequest) (*DeleteLedgerRecordResponse, error)
	GetLedgerRecordList(context.Context, *LedgerRecordListRequest) (*LedgerRecordListResponse, error)
	GetLedgerRecordDetail(context.Context, *LedgerRecordDetailRequest) (*CreateLedgerRecordResponse, error)
	// 分类操作
	CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error)
	UpdateCategory(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error)
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error)
	GetCategoryList(context.Context, *CategoryListRequest) (*CategoryListResponse, error)
	// 子分类操作
	CreateSubCategory(context.Context, *CreateSubCategoryRequest) (*CreateSubCategoryResponse, error)
	UpdateSubCategory(context.Context, *UpdateSubCategoryRequest) (*UpdateSubCategoryResponse, error)
	DeleteSubCategory(context.Context, *DeleteSubCategoryRequest) (*DeleteSubCategoryResponse, error)
	GetSubCategoryList(context.Context, *SubCategoryListRequest) (*SubCategoryListResponse, error)
	// 统计操作
	GetLedgerStatistics(context.Context, *LedgerStatisticsRequest) (*LedgerStatisticsResponse, error)
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) CreateLedgerRecord(context.Context, *CreateLedgerRecordRequest) (*CreateLedgerRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLedgerRecord not implemented")
}
func (UnimplementedLedgerServiceServer) UpdateLedgerRecord(context.Context, *UpdateLedgerRecordRequest) (*UpdateLedgerRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLedgerRecord not implemented")
}
func (UnimplementedLedgerServiceServer) DeleteLedgerRecord(context.Context, *DeleteLedgerRecordRequest) (*DeleteLedgerRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLedgerRecord not implemented")
}
func (UnimplementedLedgerServiceServer) GetLedgerRecordList(context.Context, *LedgerRecordListRequest) (*LedgerRecordListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedgerRecordList not implemented")
}
func (UnimplementedLedgerServiceServer) GetLedgerRecordDetail(context.Context, *LedgerRecordDetailRequest) (*CreateLedgerRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedgerRecordDetail not implemented")
}
func (UnimplementedLedgerServiceServer) CreateCategory(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedLedgerServiceServer) UpdateCategory(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedLedgerServiceServer) DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedLedgerServiceServer) GetCategoryList(context.Context, *CategoryListRequest) (*CategoryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryList not implemented")
}
func (UnimplementedLedgerServiceServer) CreateSubCategory(context.Context, *CreateSubCategoryRequest) (*CreateSubCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSubCategory not implemented")
}
func (UnimplementedLedgerServiceServer) UpdateSubCategory(context.Context, *UpdateSubCategoryRequest) (*UpdateSubCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSubCategory not implemented")
}
func (UnimplementedLedgerServiceServer) DeleteSubCategory(context.Context, *DeleteSubCategoryRequest) (*DeleteSubCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSubCategory not implemented")
}
func (UnimplementedLedgerServiceServer) GetSubCategoryList(context.Context, *SubCategoryListRequest) (*SubCategoryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubCategoryList not implemented")
}
func (UnimplementedLedgerServiceServer) GetLedgerStatistics(context.Context, *LedgerStatisticsRequest) (*LedgerStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedgerStatistics not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_CreateLedgerRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLedgerRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).CreateLedgerRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_CreateLedgerRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).CreateLedgerRecord(ctx, req.(*CreateLedgerRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_UpdateLedgerRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLedgerRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).UpdateLedgerRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_UpdateLedgerRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).UpdateLedgerRecord(ctx, req.(*UpdateLedgerRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_DeleteLedgerRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLedgerRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).DeleteLedgerRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_DeleteLedgerRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).DeleteLedgerRecord(ctx, req.(*DeleteLedgerRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetLedgerRecordList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedgerRecordListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetLedgerRecordList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetLedgerRecordList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetLedgerRecordList(ctx, req.(*LedgerRecordListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetLedgerRecordDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedgerRecordDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetLedgerRecordDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetLedgerRecordDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetLedgerRecordDetail(ctx, req.(*LedgerRecordDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_UpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).UpdateCategory(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).DeleteCategory(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetCategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetCategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetCategoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetCategoryList(ctx, req.(*CategoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_CreateSubCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).CreateSubCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_CreateSubCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).CreateSubCategory(ctx, req.(*CreateSubCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_UpdateSubCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).UpdateSubCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_UpdateSubCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).UpdateSubCategory(ctx, req.(*UpdateSubCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_DeleteSubCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).DeleteSubCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_DeleteSubCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).DeleteSubCategory(ctx, req.(*DeleteSubCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetSubCategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubCategoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetSubCategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetSubCategoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetSubCategoryList(ctx, req.(*SubCategoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetLedgerStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedgerStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetLedgerStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetLedgerStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetLedgerStatistics(ctx, req.(*LedgerStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLedgerRecord",
			Handler:    _LedgerService_CreateLedgerRecord_Handler,
		},
		{
			MethodName: "UpdateLedgerRecord",
			Handler:    _LedgerService_UpdateLedgerRecord_Handler,
		},
		{
			MethodName: "DeleteLedgerRecord",
			Handler:    _LedgerService_DeleteLedgerRecord_Handler,
		},
		{
			MethodName: "GetLedgerRecordList",
			Handler:    _LedgerService_GetLedgerRecordList_Handler,
		},
		{
			MethodName: "GetLedgerRecordDetail",
			Handler:    _LedgerService_GetLedgerRecordDetail_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _LedgerService_CreateCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _LedgerService_UpdateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _LedgerService_DeleteCategory_Handler,
		},
		{
			MethodName: "GetCategoryList",
			Handler:    _LedgerService_GetCategoryList_Handler,
		},
		{
			MethodName: "CreateSubCategory",
			Handler:    _LedgerService_CreateSubCategory_Handler,
		},
		{
			MethodName: "UpdateSubCategory",
			Handler:    _LedgerService_UpdateSubCategory_Handler,
		},
		{
			MethodName: "DeleteSubCategory",
			Handler:    _LedgerService_DeleteSubCategory_Handler,
		},
		{
			MethodName: "GetSubCategoryList",
			Handler:    _LedgerService_GetSubCategoryList_Handler,
		},
		{
			MethodName: "GetLedgerStatistics",
			Handler:    _LedgerService_GetLedgerStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/ledger/rpc/ledger.proto",
}
