// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: service/ledger/rpc/ledger.proto

package ledger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 记账记录消息定义
type LedgerRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	SubCategoryId int64                  `protobuf:"varint,4,opt,name=sub_category_id,json=subCategoryId,proto3" json:"sub_category_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          int64                  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"` // 1: 收入, 2: 支出
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Note          string                 `protobuf:"bytes,8,opt,name=note,proto3" json:"note,omitempty"`
	RecordDate    string                 `protobuf:"bytes,9,opt,name=record_date,json=recordDate,proto3" json:"record_date,omitempty"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Location      string                 `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty"`
	Images        []string               `protobuf:"bytes,12,rep,name=images,proto3" json:"images,omitempty"`
	Status        int64                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerRecord) Reset() {
	*x = LedgerRecord{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerRecord) ProtoMessage() {}

func (x *LedgerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerRecord.ProtoReflect.Descriptor instead.
func (*LedgerRecord) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *LedgerRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LedgerRecord) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LedgerRecord) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *LedgerRecord) GetSubCategoryId() int64 {
	if x != nil {
		return x.SubCategoryId
	}
	return 0
}

func (x *LedgerRecord) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LedgerRecord) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *LedgerRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LedgerRecord) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *LedgerRecord) GetRecordDate() string {
	if x != nil {
		return x.RecordDate
	}
	return ""
}

func (x *LedgerRecord) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *LedgerRecord) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *LedgerRecord) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *LedgerRecord) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LedgerRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LedgerRecord) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 分类消息定义
type LedgerCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Type          int64                  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"` // 1: 收入, 2: 支出
	SortOrder     int64                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	IsSystem      bool                   `protobuf:"varint,8,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	Status        int64                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerCategory) Reset() {
	*x = LedgerCategory{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerCategory) ProtoMessage() {}

func (x *LedgerCategory) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerCategory.ProtoReflect.Descriptor instead.
func (*LedgerCategory) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *LedgerCategory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LedgerCategory) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LedgerCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LedgerCategory) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *LedgerCategory) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *LedgerCategory) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *LedgerCategory) GetSortOrder() int64 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *LedgerCategory) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

func (x *LedgerCategory) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LedgerCategory) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LedgerCategory) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 子分类消息定义
type LedgerSubCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	SortOrder     int64                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        int64                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerSubCategory) Reset() {
	*x = LedgerSubCategory{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerSubCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerSubCategory) ProtoMessage() {}

func (x *LedgerSubCategory) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerSubCategory.ProtoReflect.Descriptor instead.
func (*LedgerSubCategory) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *LedgerSubCategory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LedgerSubCategory) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *LedgerSubCategory) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LedgerSubCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LedgerSubCategory) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *LedgerSubCategory) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *LedgerSubCategory) GetSortOrder() int64 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *LedgerSubCategory) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LedgerSubCategory) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LedgerSubCategory) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 记账记录相关请求响应
type CreateLedgerRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	SubCategoryId int64                  `protobuf:"varint,2,opt,name=sub_category_id,json=subCategoryId,proto3" json:"sub_category_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          int64                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Note          string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	RecordDate    string                 `protobuf:"bytes,7,opt,name=record_date,json=recordDate,proto3" json:"record_date,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Location      string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	Images        []string               `protobuf:"bytes,10,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLedgerRecordRequest) Reset() {
	*x = CreateLedgerRecordRequest{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLedgerRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLedgerRecordRequest) ProtoMessage() {}

func (x *CreateLedgerRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLedgerRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateLedgerRecordRequest) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLedgerRecordRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateLedgerRecordRequest) GetSubCategoryId() int64 {
	if x != nil {
		return x.SubCategoryId
	}
	return 0
}

func (x *CreateLedgerRecordRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateLedgerRecordRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateLedgerRecordRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateLedgerRecordRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CreateLedgerRecordRequest) GetRecordDate() string {
	if x != nil {
		return x.RecordDate
	}
	return ""
}

func (x *CreateLedgerRecordRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateLedgerRecordRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateLedgerRecordRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type CreateLedgerRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *LedgerRecord          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLedgerRecordResponse) Reset() {
	*x = CreateLedgerRecordResponse{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLedgerRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLedgerRecordResponse) ProtoMessage() {}

func (x *CreateLedgerRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLedgerRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateLedgerRecordResponse) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *CreateLedgerRecordResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateLedgerRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateLedgerRecordResponse) GetData() *LedgerRecord {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateLedgerRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	SubCategoryId int64                  `protobuf:"varint,3,opt,name=sub_category_id,json=subCategoryId,proto3" json:"sub_category_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          int64                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Note          string                 `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	RecordDate    string                 `protobuf:"bytes,8,opt,name=record_date,json=recordDate,proto3" json:"record_date,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Location      string                 `protobuf:"bytes,10,opt,name=location,proto3" json:"location,omitempty"`
	Images        []string               `protobuf:"bytes,11,rep,name=images,proto3" json:"images,omitempty"`
	Status        int64                  `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLedgerRecordRequest) Reset() {
	*x = UpdateLedgerRecordRequest{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLedgerRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLedgerRecordRequest) ProtoMessage() {}

func (x *UpdateLedgerRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLedgerRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateLedgerRecordRequest) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLedgerRecordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateLedgerRecordRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateLedgerRecordRequest) GetSubCategoryId() int64 {
	if x != nil {
		return x.SubCategoryId
	}
	return 0
}

func (x *UpdateLedgerRecordRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateLedgerRecordRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdateLedgerRecordRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateLedgerRecordRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *UpdateLedgerRecordRequest) GetRecordDate() string {
	if x != nil {
		return x.RecordDate
	}
	return ""
}

func (x *UpdateLedgerRecordRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateLedgerRecordRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateLedgerRecordRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *UpdateLedgerRecordRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateLedgerRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *LedgerRecord          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLedgerRecordResponse) Reset() {
	*x = UpdateLedgerRecordResponse{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLedgerRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLedgerRecordResponse) ProtoMessage() {}

func (x *UpdateLedgerRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLedgerRecordResponse.ProtoReflect.Descriptor instead.
func (*UpdateLedgerRecordResponse) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLedgerRecordResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateLedgerRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateLedgerRecordResponse) GetData() *LedgerRecord {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteLedgerRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLedgerRecordRequest) Reset() {
	*x = DeleteLedgerRecordRequest{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLedgerRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLedgerRecordRequest) ProtoMessage() {}

func (x *DeleteLedgerRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLedgerRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteLedgerRecordRequest) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLedgerRecordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteLedgerRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLedgerRecordResponse) Reset() {
	*x = DeleteLedgerRecordResponse{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLedgerRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLedgerRecordResponse) ProtoMessage() {}

func (x *DeleteLedgerRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLedgerRecordResponse.ProtoReflect.Descriptor instead.
func (*DeleteLedgerRecordResponse) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLedgerRecordResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteLedgerRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LedgerRecordListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Type          int64                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Keyword       string                 `protobuf:"bytes,7,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerRecordListRequest) Reset() {
	*x = LedgerRecordListRequest{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerRecordListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerRecordListRequest) ProtoMessage() {}

func (x *LedgerRecordListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerRecordListRequest.ProtoReflect.Descriptor instead.
func (*LedgerRecordListRequest) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *LedgerRecordListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *LedgerRecordListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *LedgerRecordListRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *LedgerRecordListRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *LedgerRecordListRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *LedgerRecordListRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *LedgerRecordListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type LedgerRecordListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*LedgerRecord        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerRecordListData) Reset() {
	*x = LedgerRecordListData{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerRecordListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerRecordListData) ProtoMessage() {}

func (x *LedgerRecordListData) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerRecordListData.ProtoReflect.Descriptor instead.
func (*LedgerRecordListData) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{10}
}

func (x *LedgerRecordListData) GetList() []*LedgerRecord {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *LedgerRecordListData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *LedgerRecordListData) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *LedgerRecordListData) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type LedgerRecordListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *LedgerRecordListData  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerRecordListResponse) Reset() {
	*x = LedgerRecordListResponse{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerRecordListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerRecordListResponse) ProtoMessage() {}

func (x *LedgerRecordListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerRecordListResponse.ProtoReflect.Descriptor instead.
func (*LedgerRecordListResponse) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{11}
}

func (x *LedgerRecordListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LedgerRecordListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LedgerRecordListResponse) GetData() *LedgerRecordListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LedgerRecordDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerRecordDetailRequest) Reset() {
	*x = LedgerRecordDetailRequest{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerRecordDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerRecordDetailRequest) ProtoMessage() {}

func (x *LedgerRecordDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerRecordDetailRequest.ProtoReflect.Descriptor instead.
func (*LedgerRecordDetailRequest) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{12}
}

func (x *LedgerRecordDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 分类相关请求响应
type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Type          int64                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	SortOrder     int64                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateCategoryRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateCategoryRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateCategoryRequest) GetSortOrder() int64 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type CreateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *LedgerCategory        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryResponse) Reset() {
	*x = CreateCategoryResponse{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryResponse) ProtoMessage() {}

func (x *CreateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{14}
}

func (x *CreateCategoryResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCategoryResponse) GetData() *LedgerCategory {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Type          int64                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	SortOrder     int64                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateCategoryRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *UpdateCategoryRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdateCategoryRequest) GetSortOrder() int64 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *UpdateCategoryRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *LedgerCategory        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryResponse) Reset() {
	*x = UpdateCategoryResponse{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryResponse) ProtoMessage() {}

func (x *UpdateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateCategoryResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateCategoryResponse) GetData() *LedgerCategory {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryResponse) Reset() {
	*x = DeleteCategoryResponse{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryResponse) ProtoMessage() {}

func (x *DeleteCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteCategoryResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CategoryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListRequest) Reset() {
	*x = CategoryListRequest{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListRequest) ProtoMessage() {}

func (x *CategoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListRequest.ProtoReflect.Descriptor instead.
func (*CategoryListRequest) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{19}
}

type CategoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*LedgerCategory      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListResponse) Reset() {
	*x = CategoryListResponse{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListResponse) ProtoMessage() {}

func (x *CategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListResponse.ProtoReflect.Descriptor instead.
func (*CategoryListResponse) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{20}
}

func (x *CategoryListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CategoryListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CategoryListResponse) GetData() []*LedgerCategory {
	if x != nil {
		return x.Data
	}
	return nil
}

// 子分类相关请求响应
type CreateSubCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	SortOrder     int64                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubCategoryRequest) Reset() {
	*x = CreateSubCategoryRequest{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubCategoryRequest) ProtoMessage() {}

func (x *CreateSubCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateSubCategoryRequest) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{21}
}

func (x *CreateSubCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateSubCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubCategoryRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateSubCategoryRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateSubCategoryRequest) GetSortOrder() int64 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type CreateSubCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *LedgerSubCategory     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubCategoryResponse) Reset() {
	*x = CreateSubCategoryResponse{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubCategoryResponse) ProtoMessage() {}

func (x *CreateSubCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateSubCategoryResponse) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{22}
}

func (x *CreateSubCategoryResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateSubCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateSubCategoryResponse) GetData() *LedgerSubCategory {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateSubCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	SortOrder     int64                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubCategoryRequest) Reset() {
	*x = UpdateSubCategoryRequest{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubCategoryRequest) ProtoMessage() {}

func (x *UpdateSubCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubCategoryRequest) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateSubCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSubCategoryRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateSubCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSubCategoryRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateSubCategoryRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *UpdateSubCategoryRequest) GetSortOrder() int64 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *UpdateSubCategoryRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateSubCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *LedgerSubCategory     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubCategoryResponse) Reset() {
	*x = UpdateSubCategoryResponse{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubCategoryResponse) ProtoMessage() {}

func (x *UpdateSubCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateSubCategoryResponse) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateSubCategoryResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateSubCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateSubCategoryResponse) GetData() *LedgerSubCategory {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteSubCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubCategoryRequest) Reset() {
	*x = DeleteSubCategoryRequest{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubCategoryRequest) ProtoMessage() {}

func (x *DeleteSubCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubCategoryRequest) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteSubCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSubCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubCategoryResponse) Reset() {
	*x = DeleteSubCategoryResponse{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubCategoryResponse) ProtoMessage() {}

func (x *DeleteSubCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteSubCategoryResponse) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteSubCategoryResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteSubCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubCategoryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubCategoryListRequest) Reset() {
	*x = SubCategoryListRequest{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCategoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCategoryListRequest) ProtoMessage() {}

func (x *SubCategoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCategoryListRequest.ProtoReflect.Descriptor instead.
func (*SubCategoryListRequest) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{27}
}

func (x *SubCategoryListRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type SubCategoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*LedgerSubCategory   `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubCategoryListResponse) Reset() {
	*x = SubCategoryListResponse{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCategoryListResponse) ProtoMessage() {}

func (x *SubCategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCategoryListResponse.ProtoReflect.Descriptor instead.
func (*SubCategoryListResponse) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{28}
}

func (x *SubCategoryListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SubCategoryListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubCategoryListResponse) GetData() []*LedgerSubCategory {
	if x != nil {
		return x.Data
	}
	return nil
}

// 统计相关
type LedgerStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Type          int64                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerStatisticsRequest) Reset() {
	*x = LedgerStatisticsRequest{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerStatisticsRequest) ProtoMessage() {}

func (x *LedgerStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerStatisticsRequest.ProtoReflect.Descriptor instead.
func (*LedgerStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{29}
}

func (x *LedgerStatisticsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *LedgerStatisticsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *LedgerStatisticsRequest) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type CategoryStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Percentage    float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryStatistics) Reset() {
	*x = CategoryStatistics{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryStatistics) ProtoMessage() {}

func (x *CategoryStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryStatistics.ProtoReflect.Descriptor instead.
func (*CategoryStatistics) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{30}
}

func (x *CategoryStatistics) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategoryStatistics) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategoryStatistics) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CategoryStatistics) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type LedgerStatisticsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalIncome   float64                `protobuf:"fixed64,1,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpense  float64                `protobuf:"fixed64,2,opt,name=total_expense,json=totalExpense,proto3" json:"total_expense,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	CategoryStats []*CategoryStatistics  `protobuf:"bytes,4,rep,name=category_stats,json=categoryStats,proto3" json:"category_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerStatisticsData) Reset() {
	*x = LedgerStatisticsData{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerStatisticsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerStatisticsData) ProtoMessage() {}

func (x *LedgerStatisticsData) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerStatisticsData.ProtoReflect.Descriptor instead.
func (*LedgerStatisticsData) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{31}
}

func (x *LedgerStatisticsData) GetTotalIncome() float64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *LedgerStatisticsData) GetTotalExpense() float64 {
	if x != nil {
		return x.TotalExpense
	}
	return 0
}

func (x *LedgerStatisticsData) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *LedgerStatisticsData) GetCategoryStats() []*CategoryStatistics {
	if x != nil {
		return x.CategoryStats
	}
	return nil
}

type LedgerStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *LedgerStatisticsData  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerStatisticsResponse) Reset() {
	*x = LedgerStatisticsResponse{}
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerStatisticsResponse) ProtoMessage() {}

func (x *LedgerStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ledger_rpc_ledger_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerStatisticsResponse.ProtoReflect.Descriptor instead.
func (*LedgerStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_service_ledger_rpc_ledger_proto_rawDescGZIP(), []int{32}
}

func (x *LedgerStatisticsResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LedgerStatisticsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LedgerStatisticsResponse) GetData() *LedgerStatisticsData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_service_ledger_rpc_ledger_proto protoreflect.FileDescriptor

const file_service_ledger_rpc_ledger_proto_rawDesc = "" +
	"\n" +
	"\x1fservice/ledger/rpc/ledger.proto\x12\x06ledger\"\xa1\x03\n" +
	"\fLedgerRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x12&\n" +
	"\x0fsub_category_id\x18\x04 \x01(\x03R\rsubCategoryId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04type\x18\x06 \x01(\x03R\x04type\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x12\n" +
	"\x04note\x18\b \x01(\tR\x04note\x12\x1f\n" +
	"\vrecord_date\x18\t \x01(\tR\n" +
	"recordDate\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12\x1a\n" +
	"\blocation\x18\v \x01(\tR\blocation\x12\x16\n" +
	"\x06images\x18\f \x03(\tR\x06images\x12\x16\n" +
	"\x06status\x18\r \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\"\x9d\x02\n" +
	"\x0eLedgerCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12\x12\n" +
	"\x04type\x18\x06 \x01(\x03R\x04type\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x03R\tsortOrder\x12\x1b\n" +
	"\tis_system\x18\b \x01(\bR\bisSystem\x12\x16\n" +
	"\x06status\x18\t \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"\x90\x02\n" +
	"\x11LedgerSubCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x03R\tsortOrder\x12\x16\n" +
	"\x06status\x18\b \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xaf\x02\n" +
	"\x19CreateLedgerRecordRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12&\n" +
	"\x0fsub_category_id\x18\x02 \x01(\x03R\rsubCategoryId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x03R\x04type\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12\x1f\n" +
	"\vrecord_date\x18\a \x01(\tR\n" +
	"recordDate\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12\x16\n" +
	"\x06images\x18\n" +
	" \x03(\tR\x06images\"t\n" +
	"\x1aCreateLedgerRecordResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.ledger.LedgerRecordR\x04data\"\xd7\x02\n" +
	"\x19UpdateLedgerRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12&\n" +
	"\x0fsub_category_id\x18\x03 \x01(\x03R\rsubCategoryId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x03R\x04type\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\x12\x1f\n" +
	"\vrecord_date\x18\b \x01(\tR\n" +
	"recordDate\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x1a\n" +
	"\blocation\x18\n" +
	" \x01(\tR\blocation\x12\x16\n" +
	"\x06images\x18\v \x03(\tR\x06images\x12\x16\n" +
	"\x06status\x18\f \x01(\x03R\x06status\"t\n" +
	"\x1aUpdateLedgerRecordResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.ledger.LedgerRecordR\x04data\"+\n" +
	"\x19DeleteLedgerRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"J\n" +
	"\x1aDeleteLedgerRecordResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd3\x01\n" +
	"\x17LedgerRecordListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x03R\x04type\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x18\n" +
	"\akeyword\x18\a \x01(\tR\akeyword\"\x87\x01\n" +
	"\x14LedgerRecordListData\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.ledger.LedgerRecordR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x03R\bpageSize\"z\n" +
	"\x18LedgerRecordListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x04data\x18\x03 \x01(\v2\x1c.ledger.LedgerRecordListDataR\x04data\"+\n" +
	"\x19LedgerRecordDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x88\x01\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x02 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x03R\x04type\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x03R\tsortOrder\"r\n" +
	"\x16CreateCategoryResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x16.ledger.LedgerCategoryR\x04data\"\xb0\x01\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x03R\x04type\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x03R\tsortOrder\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\"r\n" +
	"\x16UpdateCategoryResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x16.ledger.LedgerCategoryR\x04data\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"F\n" +
	"\x16DeleteCategoryResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x15\n" +
	"\x13CategoryListRequest\"p\n" +
	"\x14CategoryListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04data\x18\x03 \x03(\v2\x16.ledger.LedgerCategoryR\x04data\"\x98\x01\n" +
	"\x18CreateSubCategoryRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x03R\tsortOrder\"x\n" +
	"\x19CreateSubCategoryResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.ledger.LedgerSubCategoryR\x04data\"\xc0\x01\n" +
	"\x18UpdateSubCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x03R\tsortOrder\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\"x\n" +
	"\x19UpdateSubCategoryResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.ledger.LedgerSubCategoryR\x04data\"*\n" +
	"\x18DeleteSubCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"I\n" +
	"\x19DeleteSubCategoryResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x16SubCategoryListRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\"v\n" +
	"\x17SubCategoryListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x03(\v2\x19.ledger.LedgerSubCategoryR\x04data\"g\n" +
	"\x17LedgerStatisticsRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x03R\x04type\"\x92\x01\n" +
	"\x12CategoryStatistics\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\"\xbb\x01\n" +
	"\x14LedgerStatisticsData\x12!\n" +
	"\ftotal_income\x18\x01 \x01(\x01R\vtotalIncome\x12#\n" +
	"\rtotal_expense\x18\x02 \x01(\x01R\ftotalExpense\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x12A\n" +
	"\x0ecategory_stats\x18\x04 \x03(\v2\x1a.ledger.CategoryStatisticsR\rcategoryStats\"z\n" +
	"\x18LedgerStatisticsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x04data\x18\x03 \x01(\v2\x1c.ledger.LedgerStatisticsDataR\x04data2\xe0\t\n" +
	"\rLedgerService\x12[\n" +
	"\x12CreateLedgerRecord\x12!.ledger.CreateLedgerRecordRequest\x1a\".ledger.CreateLedgerRecordResponse\x12[\n" +
	"\x12UpdateLedgerRecord\x12!.ledger.UpdateLedgerRecordRequest\x1a\".ledger.UpdateLedgerRecordResponse\x12[\n" +
	"\x12DeleteLedgerRecord\x12!.ledger.DeleteLedgerRecordRequest\x1a\".ledger.DeleteLedgerRecordResponse\x12X\n" +
	"\x13GetLedgerRecordList\x12\x1f.ledger.LedgerRecordListRequest\x1a .ledger.LedgerRecordListResponse\x12^\n" +
	"\x15GetLedgerRecordDetail\x12!.ledger.LedgerRecordDetailRequest\x1a\".ledger.CreateLedgerRecordResponse\x12O\n" +
	"\x0eCreateCategory\x12\x1d.ledger.CreateCategoryRequest\x1a\x1e.ledger.CreateCategoryResponse\x12O\n" +
	"\x0eUpdateCategory\x12\x1d.ledger.UpdateCategoryRequest\x1a\x1e.ledger.UpdateCategoryResponse\x12O\n" +
	"\x0eDeleteCategory\x12\x1d.ledger.DeleteCategoryRequest\x1a\x1e.ledger.DeleteCategoryResponse\x12L\n" +
	"\x0fGetCategoryList\x12\x1b.ledger.CategoryListRequest\x1a\x1c.ledger.CategoryListResponse\x12X\n" +
	"\x11CreateSubCategory\x12 .ledger.CreateSubCategoryRequest\x1a!.ledger.CreateSubCategoryResponse\x12X\n" +
	"\x11UpdateSubCategory\x12 .ledger.UpdateSubCategoryRequest\x1a!.ledger.UpdateSubCategoryResponse\x12X\n" +
	"\x11DeleteSubCategory\x12 .ledger.DeleteSubCategoryRequest\x1a!.ledger.DeleteSubCategoryResponse\x12U\n" +
	"\x12GetSubCategoryList\x12\x1e.ledger.SubCategoryListRequest\x1a\x1f.ledger.SubCategoryListResponse\x12X\n" +
	"\x13GetLedgerStatistics\x12\x1f.ledger.LedgerStatisticsRequest\x1a .ledger.LedgerStatisticsResponseB\n" +
	"Z\b./ledgerb\x06proto3"

var (
	file_service_ledger_rpc_ledger_proto_rawDescOnce sync.Once
	file_service_ledger_rpc_ledger_proto_rawDescData []byte
)

func file_service_ledger_rpc_ledger_proto_rawDescGZIP() []byte {
	file_service_ledger_rpc_ledger_proto_rawDescOnce.Do(func() {
		file_service_ledger_rpc_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_ledger_rpc_ledger_proto_rawDesc), len(file_service_ledger_rpc_ledger_proto_rawDesc)))
	})
	return file_service_ledger_rpc_ledger_proto_rawDescData
}

var file_service_ledger_rpc_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_service_ledger_rpc_ledger_proto_goTypes = []any{
	(*LedgerRecord)(nil),               // 0: ledger.LedgerRecord
	(*LedgerCategory)(nil),             // 1: ledger.LedgerCategory
	(*LedgerSubCategory)(nil),          // 2: ledger.LedgerSubCategory
	(*CreateLedgerRecordRequest)(nil),  // 3: ledger.CreateLedgerRecordRequest
	(*CreateLedgerRecordResponse)(nil), // 4: ledger.CreateLedgerRecordResponse
	(*UpdateLedgerRecordRequest)(nil),  // 5: ledger.UpdateLedgerRecordRequest
	(*UpdateLedgerRecordResponse)(nil), // 6: ledger.UpdateLedgerRecordResponse
	(*DeleteLedgerRecordRequest)(nil),  // 7: ledger.DeleteLedgerRecordRequest
	(*DeleteLedgerRecordResponse)(nil), // 8: ledger.DeleteLedgerRecordResponse
	(*LedgerRecordListRequest)(nil),    // 9: ledger.LedgerRecordListRequest
	(*LedgerRecordListData)(nil),       // 10: ledger.LedgerRecordListData
	(*LedgerRecordListResponse)(nil),   // 11: ledger.LedgerRecordListResponse
	(*LedgerRecordDetailRequest)(nil),  // 12: ledger.LedgerRecordDetailRequest
	(*CreateCategoryRequest)(nil),      // 13: ledger.CreateCategoryRequest
	(*CreateCategoryResponse)(nil),     // 14: ledger.CreateCategoryResponse
	(*UpdateCategoryRequest)(nil),      // 15: ledger.UpdateCategoryRequest
	(*UpdateCategoryResponse)(nil),     // 16: ledger.UpdateCategoryResponse
	(*DeleteCategoryRequest)(nil),      // 17: ledger.DeleteCategoryRequest
	(*DeleteCategoryResponse)(nil),     // 18: ledger.DeleteCategoryResponse
	(*CategoryListRequest)(nil),        // 19: ledger.CategoryListRequest
	(*CategoryListResponse)(nil),       // 20: ledger.CategoryListResponse
	(*CreateSubCategoryRequest)(nil),   // 21: ledger.CreateSubCategoryRequest
	(*CreateSubCategoryResponse)(nil),  // 22: ledger.CreateSubCategoryResponse
	(*UpdateSubCategoryRequest)(nil),   // 23: ledger.UpdateSubCategoryRequest
	(*UpdateSubCategoryResponse)(nil),  // 24: ledger.UpdateSubCategoryResponse
	(*DeleteSubCategoryRequest)(nil),   // 25: ledger.DeleteSubCategoryRequest
	(*DeleteSubCategoryResponse)(nil),  // 26: ledger.DeleteSubCategoryResponse
	(*SubCategoryListRequest)(nil),     // 27: ledger.SubCategoryListRequest
	(*SubCategoryListResponse)(nil),    // 28: ledger.SubCategoryListResponse
	(*LedgerStatisticsRequest)(nil),    // 29: ledger.LedgerStatisticsRequest
	(*CategoryStatistics)(nil),         // 30: ledger.CategoryStatistics
	(*LedgerStatisticsData)(nil),       // 31: ledger.LedgerStatisticsData
	(*LedgerStatisticsResponse)(nil),   // 32: ledger.LedgerStatisticsResponse
}
var file_service_ledger_rpc_ledger_proto_depIdxs = []int32{
	0,  // 0: ledger.CreateLedgerRecordResponse.data:type_name -> ledger.LedgerRecord
	0,  // 1: ledger.UpdateLedgerRecordResponse.data:type_name -> ledger.LedgerRecord
	0,  // 2: ledger.LedgerRecordListData.list:type_name -> ledger.LedgerRecord
	10, // 3: ledger.LedgerRecordListResponse.data:type_name -> ledger.LedgerRecordListData
	1,  // 4: ledger.CreateCategoryResponse.data:type_name -> ledger.LedgerCategory
	1,  // 5: ledger.UpdateCategoryResponse.data:type_name -> ledger.LedgerCategory
	1,  // 6: ledger.CategoryListResponse.data:type_name -> ledger.LedgerCategory
	2,  // 7: ledger.CreateSubCategoryResponse.data:type_name -> ledger.LedgerSubCategory
	2,  // 8: ledger.UpdateSubCategoryResponse.data:type_name -> ledger.LedgerSubCategory
	2,  // 9: ledger.SubCategoryListResponse.data:type_name -> ledger.LedgerSubCategory
	30, // 10: ledger.LedgerStatisticsData.category_stats:type_name -> ledger.CategoryStatistics
	31, // 11: ledger.LedgerStatisticsResponse.data:type_name -> ledger.LedgerStatisticsData
	3,  // 12: ledger.LedgerService.CreateLedgerRecord:input_type -> ledger.CreateLedgerRecordRequest
	5,  // 13: ledger.LedgerService.UpdateLedgerRecord:input_type -> ledger.UpdateLedgerRecordRequest
	7,  // 14: ledger.LedgerService.DeleteLedgerRecord:input_type -> ledger.DeleteLedgerRecordRequest
	9,  // 15: ledger.LedgerService.GetLedgerRecordList:input_type -> ledger.LedgerRecordListRequest
	12, // 16: ledger.LedgerService.GetLedgerRecordDetail:input_type -> ledger.LedgerRecordDetailRequest
	13, // 17: ledger.LedgerService.CreateCategory:input_type -> ledger.CreateCategoryRequest
	15, // 18: ledger.LedgerService.UpdateCategory:input_type -> ledger.UpdateCategoryRequest
	17, // 19: ledger.LedgerService.DeleteCategory:input_type -> ledger.DeleteCategoryRequest
	19, // 20: ledger.LedgerService.GetCategoryList:input_type -> ledger.CategoryListRequest
	21, // 21: ledger.LedgerService.CreateSubCategory:input_type -> ledger.CreateSubCategoryRequest
	23, // 22: ledger.LedgerService.UpdateSubCategory:input_type -> ledger.UpdateSubCategoryRequest
	25, // 23: ledger.LedgerService.DeleteSubCategory:input_type -> ledger.DeleteSubCategoryRequest
	27, // 24: ledger.LedgerService.GetSubCategoryList:input_type -> ledger.SubCategoryListRequest
	29, // 25: ledger.LedgerService.GetLedgerStatistics:input_type -> ledger.LedgerStatisticsRequest
	4,  // 26: ledger.LedgerService.CreateLedgerRecord:output_type -> ledger.CreateLedgerRecordResponse
	6,  // 27: ledger.LedgerService.UpdateLedgerRecord:output_type -> ledger.UpdateLedgerRecordResponse
	8,  // 28: ledger.LedgerService.DeleteLedgerRecord:output_type -> ledger.DeleteLedgerRecordResponse
	11, // 29: ledger.LedgerService.GetLedgerRecordList:output_type -> ledger.LedgerRecordListResponse
	4,  // 30: ledger.LedgerService.GetLedgerRecordDetail:output_type -> ledger.CreateLedgerRecordResponse
	14, // 31: ledger.LedgerService.CreateCategory:output_type -> ledger.CreateCategoryResponse
	16, // 32: ledger.LedgerService.UpdateCategory:output_type -> ledger.UpdateCategoryResponse
	18, // 33: ledger.LedgerService.DeleteCategory:output_type -> ledger.DeleteCategoryResponse
	20, // 34: ledger.LedgerService.GetCategoryList:output_type -> ledger.CategoryListResponse
	22, // 35: ledger.LedgerService.CreateSubCategory:output_type -> ledger.CreateSubCategoryResponse
	24, // 36: ledger.LedgerService.UpdateSubCategory:output_type -> ledger.UpdateSubCategoryResponse
	26, // 37: ledger.LedgerService.DeleteSubCategory:output_type -> ledger.DeleteSubCategoryResponse
	28, // 38: ledger.LedgerService.GetSubCategoryList:output_type -> ledger.SubCategoryListResponse
	32, // 39: ledger.LedgerService.GetLedgerStatistics:output_type -> ledger.LedgerStatisticsResponse
	26, // [26:40] is the sub-list for method output_type
	12, // [12:26] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_service_ledger_rpc_ledger_proto_init() }
func file_service_ledger_rpc_ledger_proto_init() {
	if File_service_ledger_rpc_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_ledger_rpc_ledger_proto_rawDesc), len(file_service_ledger_rpc_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_ledger_rpc_ledger_proto_goTypes,
		DependencyIndexes: file_service_ledger_rpc_ledger_proto_depIdxs,
		MessageInfos:      file_service_ledger_rpc_ledger_proto_msgTypes,
	}.Build()
	File_service_ledger_rpc_ledger_proto = out.File
	file_service_ledger_rpc_ledger_proto_goTypes = nil
	file_service_ledger_rpc_ledger_proto_depIdxs = nil
}
