// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ledger.proto

package ledgerservice

import (
	"context"

	"xledger/service/ledger/rpc/ledger"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CategoryListRequest        = ledger.CategoryListRequest
	CategoryListResponse       = ledger.CategoryListResponse
	CategoryStatistics         = ledger.CategoryStatistics
	CreateCategoryRequest      = ledger.CreateCategoryRequest
	CreateCategoryResponse     = ledger.CreateCategoryResponse
	CreateLedgerRecordRequest  = ledger.CreateLedgerRecordRequest
	CreateLedgerRecordResponse = ledger.CreateLedgerRecordResponse
	CreateSubCategoryRequest   = ledger.CreateSubCategoryRequest
	CreateSubCategoryResponse  = ledger.CreateSubCategoryResponse
	DeleteCategoryRequest      = ledger.DeleteCategoryRequest
	DeleteCategoryResponse     = ledger.DeleteCategoryResponse
	DeleteLedgerRecordRequest  = ledger.DeleteLedgerRecordRequest
	DeleteLedgerRecordResponse = ledger.DeleteLedgerRecordResponse
	DeleteSubCategoryRequest   = ledger.DeleteSubCategoryRequest
	DeleteSubCategoryResponse  = ledger.DeleteSubCategoryResponse
	LedgerCategory             = ledger.LedgerCategory
	LedgerRecord               = ledger.LedgerRecord
	LedgerRecordDetailRequest  = ledger.LedgerRecordDetailRequest
	LedgerRecordListData       = ledger.LedgerRecordListData
	LedgerRecordListRequest    = ledger.LedgerRecordListRequest
	LedgerRecordListResponse   = ledger.LedgerRecordListResponse
	LedgerStatisticsData       = ledger.LedgerStatisticsData
	LedgerStatisticsRequest    = ledger.LedgerStatisticsRequest
	LedgerStatisticsResponse   = ledger.LedgerStatisticsResponse
	LedgerSubCategory          = ledger.LedgerSubCategory
	SubCategoryListRequest     = ledger.SubCategoryListRequest
	SubCategoryListResponse    = ledger.SubCategoryListResponse
	UpdateCategoryRequest      = ledger.UpdateCategoryRequest
	UpdateCategoryResponse     = ledger.UpdateCategoryResponse
	UpdateLedgerRecordRequest  = ledger.UpdateLedgerRecordRequest
	UpdateLedgerRecordResponse = ledger.UpdateLedgerRecordResponse
	UpdateSubCategoryRequest   = ledger.UpdateSubCategoryRequest
	UpdateSubCategoryResponse  = ledger.UpdateSubCategoryResponse

	LedgerService interface {
		// 记账记录操作
		CreateLedgerRecord(ctx context.Context, in *CreateLedgerRecordRequest, opts ...grpc.CallOption) (*CreateLedgerRecordResponse, error)
		UpdateLedgerRecord(ctx context.Context, in *UpdateLedgerRecordRequest, opts ...grpc.CallOption) (*UpdateLedgerRecordResponse, error)
		DeleteLedgerRecord(ctx context.Context, in *DeleteLedgerRecordRequest, opts ...grpc.CallOption) (*DeleteLedgerRecordResponse, error)
		GetLedgerRecordList(ctx context.Context, in *LedgerRecordListRequest, opts ...grpc.CallOption) (*LedgerRecordListResponse, error)
		GetLedgerRecordDetail(ctx context.Context, in *LedgerRecordDetailRequest, opts ...grpc.CallOption) (*CreateLedgerRecordResponse, error)
		// 分类操作
		CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
		UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
		DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
		GetCategoryList(ctx context.Context, in *CategoryListRequest, opts ...grpc.CallOption) (*CategoryListResponse, error)
		// 子分类操作
		CreateSubCategory(ctx context.Context, in *CreateSubCategoryRequest, opts ...grpc.CallOption) (*CreateSubCategoryResponse, error)
		UpdateSubCategory(ctx context.Context, in *UpdateSubCategoryRequest, opts ...grpc.CallOption) (*UpdateSubCategoryResponse, error)
		DeleteSubCategory(ctx context.Context, in *DeleteSubCategoryRequest, opts ...grpc.CallOption) (*DeleteSubCategoryResponse, error)
		GetSubCategoryList(ctx context.Context, in *SubCategoryListRequest, opts ...grpc.CallOption) (*SubCategoryListResponse, error)
		// 统计操作
		GetLedgerStatistics(ctx context.Context, in *LedgerStatisticsRequest, opts ...grpc.CallOption) (*LedgerStatisticsResponse, error)
	}

	defaultLedgerService struct {
		cli zrpc.Client
	}
)

func NewLedgerService(cli zrpc.Client) LedgerService {
	return &defaultLedgerService{
		cli: cli,
	}
}

// 记账记录操作
func (m *defaultLedgerService) CreateLedgerRecord(ctx context.Context, in *CreateLedgerRecordRequest, opts ...grpc.CallOption) (*CreateLedgerRecordResponse, error) {
	client := ledger.NewLedgerServiceClient(m.cli.Conn())
	return client.CreateLedgerRecord(ctx, in, opts...)
}

func (m *defaultLedgerService) UpdateLedgerRecord(ctx context.Context, in *UpdateLedgerRecordRequest, opts ...grpc.CallOption) (*UpdateLedgerRecordResponse, error) {
	client := ledger.NewLedgerServiceClient(m.cli.Conn())
	return client.UpdateLedgerRecord(ctx, in, opts...)
}

func (m *defaultLedgerService) DeleteLedgerRecord(ctx context.Context, in *DeleteLedgerRecordRequest, opts ...grpc.CallOption) (*DeleteLedgerRecordResponse, error) {
	client := ledger.NewLedgerServiceClient(m.cli.Conn())
	return client.DeleteLedgerRecord(ctx, in, opts...)
}

func (m *defaultLedgerService) GetLedgerRecordList(ctx context.Context, in *LedgerRecordListRequest, opts ...grpc.CallOption) (*LedgerRecordListResponse, error) {
	client := ledger.NewLedgerServiceClient(m.cli.Conn())
	return client.GetLedgerRecordList(ctx, in, opts...)
}

func (m *defaultLedgerService) GetLedgerRecordDetail(ctx context.Context, in *LedgerRecordDetailRequest, opts ...grpc.CallOption) (*CreateLedgerRecordResponse, error) {
	client := ledger.NewLedgerServiceClient(m.cli.Conn())
	return client.GetLedgerRecordDetail(ctx, in, opts...)
}

// 分类操作
func (m *defaultLedgerService) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	client := ledger.NewLedgerServiceClient(m.cli.Conn())
	return client.CreateCategory(ctx, in, opts...)
}

func (m *defaultLedgerService) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	client := ledger.NewLedgerServiceClient(m.cli.Conn())
	return client.UpdateCategory(ctx, in, opts...)
}

func (m *defaultLedgerService) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	client := ledger.NewLedgerServiceClient(m.cli.Conn())
	return client.DeleteCategory(ctx, in, opts...)
}

func (m *defaultLedgerService) GetCategoryList(ctx context.Context, in *CategoryListRequest, opts ...grpc.CallOption) (*CategoryListResponse, error) {
	client := ledger.NewLedgerServiceClient(m.cli.Conn())
	return client.GetCategoryList(ctx, in, opts...)
}

// 子分类操作
func (m *defaultLedgerService) CreateSubCategory(ctx context.Context, in *CreateSubCategoryRequest, opts ...grpc.CallOption) (*CreateSubCategoryResponse, error) {
	client := ledger.NewLedgerServiceClient(m.cli.Conn())
	return client.CreateSubCategory(ctx, in, opts...)
}

func (m *defaultLedgerService) UpdateSubCategory(ctx context.Context, in *UpdateSubCategoryRequest, opts ...grpc.CallOption) (*UpdateSubCategoryResponse, error) {
	client := ledger.NewLedgerServiceClient(m.cli.Conn())
	return client.UpdateSubCategory(ctx, in, opts...)
}

func (m *defaultLedgerService) DeleteSubCategory(ctx context.Context, in *DeleteSubCategoryRequest, opts ...grpc.CallOption) (*DeleteSubCategoryResponse, error) {
	client := ledger.NewLedgerServiceClient(m.cli.Conn())
	return client.DeleteSubCategory(ctx, in, opts...)
}

func (m *defaultLedgerService) GetSubCategoryList(ctx context.Context, in *SubCategoryListRequest, opts ...grpc.CallOption) (*SubCategoryListResponse, error) {
	client := ledger.NewLedgerServiceClient(m.cli.Conn())
	return client.GetSubCategoryList(ctx, in, opts...)
}

// 统计操作
func (m *defaultLedgerService) GetLedgerStatistics(ctx context.Context, in *LedgerStatisticsRequest, opts ...grpc.CallOption) (*LedgerStatisticsResponse, error) {
	client := ledger.NewLedgerServiceClient(m.cli.Conn())
	return client.GetLedgerStatistics(ctx, in, opts...)
}
