// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	ledger "xledger/service/ledger/api/internal/handler/ledger"
	"xledger/service/ledger/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/ledger/categories",
					Handler: ledger.CreateCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/ledger/categories",
					Handler: ledger.CategoryListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/ledger/categories/:id",
					Handler: ledger.UpdateCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/ledger/categories/:id",
					Handler: ledger.DeleteCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/ledger/records",
					Handler: ledger.CreateLedgerRecordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/ledger/records",
					Handler: ledger.LedgerRecordListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/ledger/records/:id",
					Handler: ledger.UpdateLedgerRecordHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/ledger/records/:id",
					Handler: ledger.DeleteLedgerRecordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/ledger/records/:id",
					Handler: ledger.LedgerRecordDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/ledger/statistics",
					Handler: ledger.LedgerStatisticsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/ledger/subcategories",
					Handler: ledger.CreateSubCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/ledger/subcategories",
					Handler: ledger.SubCategoryListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/ledger/subcategories/:id",
					Handler: ledger.UpdateSubCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/ledger/subcategories/:id",
					Handler: ledger.DeleteSubCategoryHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
