// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ledger.proto

package server

import (
	"context"

	"xledger/service/ledger/rpc/internal/logic"
	"xledger/service/ledger/rpc/internal/svc"
	"xledger/service/ledger/rpc/ledger"
)

type LedgerServiceServer struct {
	svcCtx *svc.ServiceContext
	ledger.UnimplementedLedgerServiceServer
}

func NewLedgerServiceServer(svcCtx *svc.ServiceContext) *LedgerServiceServer {
	return &LedgerServiceServer{
		svcCtx: svcCtx,
	}
}

// 记账记录操作
func (s *LedgerServiceServer) CreateLedgerRecord(ctx context.Context, in *ledger.CreateLedgerRecordRequest) (*ledger.CreateLedgerRecordResponse, error) {
	l := logic.NewCreateLedgerRecordLogic(ctx, s.svcCtx)
	return l.CreateLedgerRecord(in)
}

func (s *LedgerServiceServer) UpdateLedgerRecord(ctx context.Context, in *ledger.UpdateLedgerRecordRequest) (*ledger.UpdateLedgerRecordResponse, error) {
	l := logic.NewUpdateLedgerRecordLogic(ctx, s.svcCtx)
	return l.UpdateLedgerRecord(in)
}

func (s *LedgerServiceServer) DeleteLedgerRecord(ctx context.Context, in *ledger.DeleteLedgerRecordRequest) (*ledger.DeleteLedgerRecordResponse, error) {
	l := logic.NewDeleteLedgerRecordLogic(ctx, s.svcCtx)
	return l.DeleteLedgerRecord(in)
}

func (s *LedgerServiceServer) GetLedgerRecordList(ctx context.Context, in *ledger.LedgerRecordListRequest) (*ledger.LedgerRecordListResponse, error) {
	l := logic.NewGetLedgerRecordListLogic(ctx, s.svcCtx)
	return l.GetLedgerRecordList(in)
}

func (s *LedgerServiceServer) GetLedgerRecordDetail(ctx context.Context, in *ledger.LedgerRecordDetailRequest) (*ledger.CreateLedgerRecordResponse, error) {
	l := logic.NewGetLedgerRecordDetailLogic(ctx, s.svcCtx)
	return l.GetLedgerRecordDetail(in)
}

// 分类操作
func (s *LedgerServiceServer) CreateCategory(ctx context.Context, in *ledger.CreateCategoryRequest) (*ledger.CreateCategoryResponse, error) {
	l := logic.NewCreateCategoryLogic(ctx, s.svcCtx)
	return l.CreateCategory(in)
}

func (s *LedgerServiceServer) UpdateCategory(ctx context.Context, in *ledger.UpdateCategoryRequest) (*ledger.UpdateCategoryResponse, error) {
	l := logic.NewUpdateCategoryLogic(ctx, s.svcCtx)
	return l.UpdateCategory(in)
}

func (s *LedgerServiceServer) DeleteCategory(ctx context.Context, in *ledger.DeleteCategoryRequest) (*ledger.DeleteCategoryResponse, error) {
	l := logic.NewDeleteCategoryLogic(ctx, s.svcCtx)
	return l.DeleteCategory(in)
}

func (s *LedgerServiceServer) GetCategoryList(ctx context.Context, in *ledger.CategoryListRequest) (*ledger.CategoryListResponse, error) {
	l := logic.NewGetCategoryListLogic(ctx, s.svcCtx)
	return l.GetCategoryList(in)
}

// 子分类操作
func (s *LedgerServiceServer) CreateSubCategory(ctx context.Context, in *ledger.CreateSubCategoryRequest) (*ledger.CreateSubCategoryResponse, error) {
	l := logic.NewCreateSubCategoryLogic(ctx, s.svcCtx)
	return l.CreateSubCategory(in)
}

func (s *LedgerServiceServer) UpdateSubCategory(ctx context.Context, in *ledger.UpdateSubCategoryRequest) (*ledger.UpdateSubCategoryResponse, error) {
	l := logic.NewUpdateSubCategoryLogic(ctx, s.svcCtx)
	return l.UpdateSubCategory(in)
}

func (s *LedgerServiceServer) DeleteSubCategory(ctx context.Context, in *ledger.DeleteSubCategoryRequest) (*ledger.DeleteSubCategoryResponse, error) {
	l := logic.NewDeleteSubCategoryLogic(ctx, s.svcCtx)
	return l.DeleteSubCategory(in)
}

func (s *LedgerServiceServer) GetSubCategoryList(ctx context.Context, in *ledger.SubCategoryListRequest) (*ledger.SubCategoryListResponse, error) {
	l := logic.NewGetSubCategoryListLogic(ctx, s.svcCtx)
	return l.GetSubCategoryList(in)
}

// 统计操作
func (s *LedgerServiceServer) GetLedgerStatistics(ctx context.Context, in *ledger.LedgerStatisticsRequest) (*ledger.LedgerStatisticsResponse, error) {
	l := logic.NewGetLedgerStatisticsLogic(ctx, s.svcCtx)
	return l.GetLedgerStatistics(in)
}
