// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "xledger/service/user/api/internal/handler/auth"
	user "xledger/service/user/api/internal/handler/user"
	"xledger/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/auth/logout",
					Handler: user.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/user/:id",
					Handler: user.UserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/user/:id",
					Handler: user.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/email",
					Handler: user.ChangeEmailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/user/password",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/user/profile",
					Handler: user.UpdateProfileHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
