// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChangeEmailRequest struct {
	NewEmail string `json:"new_email" validate:"required,email"`
	Password string `json:"password" validate:"required"`
	Code     string `json:"code,optional"`
}

type ChangeEmailResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ChangePasswordRequest struct {
	OldPassword string `json:"old_password" validate:"required"`
	NewPassword string `json:"new_password" validate:"required,min=6,max=128"`
}

type ChangePasswordResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type DeleteUserRequest struct {
	Id string `path:"id"`
}

type DeleteUserResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type LoginData struct {
	User         User   `json:"user"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
	TokenType    string `json:"token_type"`
}

type LoginRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required"`
}

type LoginResponse struct {
	Code    int64     `json:"code"`
	Message string    `json:"message"`
	Data    LoginData `json:"data,omitempty"`
}

type LogoutRequest struct {
	AccessToken string `header:"Authorization" validate:"required"`
}

type LogoutResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type RegisterRequest struct {
	Username string `json:"username" validate:"required,min=2,max=50"`
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=6,max=128"`
}

type RegisterResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Data    User   `json:"data,omitempty"`
}

type UpdateProfileRequest struct {
	Username string `json:"username,optional" validate:"min=2,max=50"`
	Gender   string `json:"gender,optional"`
	Avatar   string `json:"avatar,optional"`
}

type UpdateProfileResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Data    User   `json:"data,omitempty"`
}

type User struct {
	Id        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Gender    string `json:"gender,omitempty"`
	Avatar    string `json:"avatar,omitempty"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type UserInfoRequest struct {
	Id string `path:"id"`
}

type UserInfoResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Data    User   `json:"data,omitempty"`
}
