// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	subCategoriesFieldNames          = builder.RawFieldNames(&SubCategories{}, true)
	subCategoriesRows                = strings.Join(subCategoriesFieldNames, ",")
	subCategoriesRowsExpectAutoSet   = strings.Join(stringx.Remove(subCategoriesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	subCategoriesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(subCategoriesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicSubCategoriesIdPrefix = "cache:public:subCategories:id:"
)

type (
	subCategoriesModel interface {
		Insert(ctx context.Context, data *SubCategories) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SubCategories, error)
		Update(ctx context.Context, data *SubCategories) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSubCategoriesModel struct {
		sqlc.CachedConn
		table string
	}

	SubCategories struct {
		Id         int64          `db:"id"`
		CategoryId int64          `db:"category_id"`
		UserId     int64          `db:"user_id"`
		Name       string         `db:"name"`
		Icon       sql.NullString `db:"icon"`
		Color      sql.NullString `db:"color"`
		SortOrder  int64          `db:"sort_order"`
		Status     int64          `db:"status"`
		CreatedAt  time.Time      `db:"created_at"`
		UpdatedAt  time.Time      `db:"updated_at"`
	}
)

func newSubCategoriesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSubCategoriesModel {
	return &defaultSubCategoriesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."sub_categories"`,
	}
}

func (m *defaultSubCategoriesModel) Delete(ctx context.Context, id int64) error {
	publicSubCategoriesIdKey := fmt.Sprintf("%s%v", cachePublicSubCategoriesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicSubCategoriesIdKey)
	return err
}

func (m *defaultSubCategoriesModel) FindOne(ctx context.Context, id int64) (*SubCategories, error) {
	publicSubCategoriesIdKey := fmt.Sprintf("%s%v", cachePublicSubCategoriesIdPrefix, id)
	var resp SubCategories
	err := m.QueryRowCtx(ctx, &resp, publicSubCategoriesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", subCategoriesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSubCategoriesModel) Insert(ctx context.Context, data *SubCategories) (sql.Result, error) {
	publicSubCategoriesIdKey := fmt.Sprintf("%s%v", cachePublicSubCategoriesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7)", m.table, subCategoriesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CategoryId, data.UserId, data.Name, data.Icon, data.Color, data.SortOrder, data.Status)
	}, publicSubCategoriesIdKey)
	return ret, err
}

func (m *defaultSubCategoriesModel) Update(ctx context.Context, data *SubCategories) error {
	publicSubCategoriesIdKey := fmt.Sprintf("%s%v", cachePublicSubCategoriesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, subCategoriesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.CategoryId, data.UserId, data.Name, data.Icon, data.Color, data.SortOrder, data.Status)
	}, publicSubCategoriesIdKey)
	return err
}

func (m *defaultSubCategoriesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicSubCategoriesIdPrefix, primary)
}

func (m *defaultSubCategoriesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", subCategoriesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSubCategoriesModel) tableName() string {
	return m.table
}
