// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/lib/pq"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	transactionsFieldNames          = builder.RawFieldNames(&Transactions{}, true)
	transactionsRows                = strings.Join(transactionsFieldNames, ",")
	transactionsRowsExpectAutoSet   = strings.Join(stringx.Remove(transactionsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	transactionsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(transactionsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicTransactionsIdPrefix = "cache:public:transactions:id:"
)

type (
	transactionsModel interface {
		Insert(ctx context.Context, data *Transactions) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Transactions, error)
		Update(ctx context.Context, data *Transactions) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTransactionsModel struct {
		sqlc.CachedConn
		table string
	}

	Transactions struct {
		Id              int64          `db:"id"`
		UserId          int64          `db:"user_id"`
		CategoryId      int64          `db:"category_id"`
		SubCategoryId   sql.NullInt64  `db:"sub_category_id"`
		Amount          float64        `db:"amount"`
		Type            int64          `db:"type"`
		Description     sql.NullString `db:"description"`
		Note            sql.NullString `db:"note"`
		TransactionDate time.Time      `db:"transaction_date"`
		Tags            pq.StringArray `db:"tags"`
		Location        sql.NullString `db:"location"`
		Images          pq.StringArray `db:"images"`
		Status          int64          `db:"status"`
		CreatedAt       time.Time      `db:"created_at"`
		UpdatedAt       time.Time      `db:"updated_at"`
	}
)

func newTransactionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTransactionsModel {
	return &defaultTransactionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."transactions"`,
	}
}

func (m *defaultTransactionsModel) Delete(ctx context.Context, id int64) error {
	publicTransactionsIdKey := fmt.Sprintf("%s%v", cachePublicTransactionsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicTransactionsIdKey)
	return err
}

func (m *defaultTransactionsModel) FindOne(ctx context.Context, id int64) (*Transactions, error) {
	publicTransactionsIdKey := fmt.Sprintf("%s%v", cachePublicTransactionsIdPrefix, id)
	var resp Transactions
	err := m.QueryRowCtx(ctx, &resp, publicTransactionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", transactionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTransactionsModel) Insert(ctx context.Context, data *Transactions) (sql.Result, error) {
	publicTransactionsIdKey := fmt.Sprintf("%s%v", cachePublicTransactionsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)", m.table, transactionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.CategoryId, data.SubCategoryId, data.Amount, data.Type, data.Description, data.Note, data.TransactionDate, data.Tags, data.Location, data.Images, data.Status)
	}, publicTransactionsIdKey)
	return ret, err
}

func (m *defaultTransactionsModel) Update(ctx context.Context, data *Transactions) error {
	publicTransactionsIdKey := fmt.Sprintf("%s%v", cachePublicTransactionsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, transactionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.CategoryId, data.SubCategoryId, data.Amount, data.Type, data.Description, data.Note, data.TransactionDate, data.Tags, data.Location, data.Images, data.Status)
	}, publicTransactionsIdKey)
	return err
}

func (m *defaultTransactionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicTransactionsIdPrefix, primary)
}

func (m *defaultTransactionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", transactionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTransactionsModel) tableName() string {
	return m.table
}
